### ISSUE TITLE
Captive portal incorrectly presenting "wrong room" error message

### ISSUE THREAD

**Issue by toothstone** [agdsn/hades#15]
There has been an increasing number of users reporting they saw this error message, although the correct room was assigned to them. This usually happened at the very first connection or after MAC-changes.

I know this is atm insufficient for serious debugging, I will try to collect more reports here over time.

**Comment by toothstone** [comment]
2015-11-10:
>Ich habe jetzt meine Mac Adresse auf der Internet Seite geändert jetzt sagt mir das Fenster im Browser dass ich laut Datenbank in einem anderen Zimmer wohne. Auf der log in Seite sind die Daten aber richtig

**Comment by sebschrader** [comment]
We need more information. This could not be reproduced under lab conditions.

**Comment by lukasjuhrich** [comment]
I know this is vague, but I recall this issue occurring sometimes in the time frame where the MAC-Adress has been changed in the system, but the change didn't propagate to the radius-server yet.

**Comment by sebschrader** [comment]
We could reproduce the case you mentioned under lab conditions last weekend.

In the short timeframe after a user is moved to correct room or has the correct MAC address and if the Hades database has already been refreshed to the new correct membership state, but the switch hasn't updated yet, the user will see the erroneous message.

With working CoA, we will reduce this timeframe to almost zero, but we should still fix the code that determines this error nonetheless. It should be possible to rework the error determination logic a bit.
