### ISSUE TITLE
Create ansible roles for deployment

### ISSUE THREAD

**Issue by sebschrader** [agdsn/hades#16]
It would be convenient to have Ansible roles ready to deploy Hades.

**Comment by fgrsnau** [comment]
I definitely would like to see this for v0.3. The Docker development instance is great, but not suitable for deployment.

**Comment by fgrsnau** [comment]
Internal ansible role is available and almost ready. Unfortunately, it is also dependent on our specific configuration.

I think after finalization we could include an example ansible role in our code base.
