### ISSUE TITLE
Add *~ to .gitignore

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/hades#32]
I saw some backup files (?) in `/docs/source/`. If they're not supposed to be there, one should remove them and add `*~` to the `.gitignore`.

**Comment by sebschrader** [comment]
The backup files have been deleted in 694a1e7727b345c55438687d1a961b7b2655d067

`*~` has been present in the `.gitignore` since the very beginning ec86e962868ecbd517be36cc15984bcc623dc6db
