### ISSUE TITLE
Create Debian packages

### ISSUE THREAD

**Issue by sebschrader** [agdsn/hades#37]
To make deployments and updates very easy, we should create Debian packages for Hades.

[dh_virtualenv](http://dh-virtualenv.readthedocs.io/en/latest/) looks like the easiest solution for this task. Other options are [fpm](https://github.com/jordansissel/fpm) and [stdeb](https://github.com/astraw/stdeb)

These solutions are not how official Python packages are build in Debian. The [Debian Python Policy](https://www.debian.org/doc/packaging-manuals/python-policy/) and the [Debian Wiki](https://wiki.debian.org/Python/LibraryStyleGuide) provide information on this subject.

I'm unsure if our Python and JavaScript dependencies should be provided through Debian packages (see  #18) or if we should obtain them from `PyPI` and `bower`.

Debian packages would also solve most of #16

**Comment by lukasjuhrich** [comment]
@sebschrader Hasn't a lot of this already been resolved? I saw you build debian-related things like half a year ago. What's the progress of this issue?

**Comment by fgrsnau** [comment]
This was actually fixed quite some time ago. Debian specific changes/packaging already hit `master`.
