### ISSUE TITLE
Upgrade to Debian Stretch

### ISSUE THREAD

**Issue by sebschrader** [agdsn/hades#48]
The Debian Stretch release is just around the corner and provides a lot interesting features for us:

- the MySQL foreign data wrapper is packaged
- ISC Kea is packaged

There will be quite some work to upgrade to FreeRADIUS 3.x, because the config file format changed a lot.

**Comment by sebschrader** [comment]
All services are running with Stretch so far. We need testing however, if it actually works. Looking forward for to see your tests rebased on top of this, @fgrsnau .

**Comment by fgrsnau** [comment]
Already merged, all my tests are passing.
