### ISSUE TITLE
Hades deputy is leaking database connections

### ISSUE THREAD

**Issue by sebschrader** [agdsn/hades#55]
After running for a while, the hades-deputy accumulates database connections.

The underlying cause seems to be, that database connections are not cleaned up properly, if exceptions are raised during a DBus RPC.

Transient failures, e.g. database being temporarily unavailable, cause more and more dead connections to be present.

**Comment by fgrsnau** [comment]
Does e758e1e (already hit master) completely fix this issue, @sebschrader?

**Comment by sebschrader** [comment]
This is working fine in production for a while now.
