### ISSUE TITLE
Syslog identifier is overriden by keepalived

### ISSUE THREAD

**Issue by fgrsnau** [agdsn/hades#61]
The syslog identifier for all three keepalived instances is set to `Keepalived_vrrp` which makes reading the log files more complicated. This is especially problematic as our remote syslog setup is unable to separate the messages.

EDIT: Keepalived does not print to stdout/stderr and uses syslog by itself. Unfortunately, the identifier is hard-coded.

**Comment by sebschrader** [comment]
I don't see what we could do about this.

**Comment by sebschrader** [comment]
Keepalived has an `instance` option, which is incorporated into the syslog identifier.

It will still override the syslog identifier, but at least with a meaningful distinguisher.
