### ISSUE TITLE
Implement a task providing system information

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/hades#65]
Due to mismatching celery versions, it happened multiple times to me that I was looking for an error that was purely based on incompatability.

It would be nice if the Hades agent would implement a task such as `system_information` or `version` providing e.g. the python and celery version.

**Comment by sebschrader** [comment]
Yup. Totally agree with that some more RPC functions are necessary.

Not sure though that having a Celery-based API which gives you the Celery version helps you when Celery versions mismatch and you can't communicate properly.

**Comment by sebschrader** [comment]
I've implemented two rather verbose tasks that dump everything, that is readily available. See if you need more information/a different format etc.
