### ISSUE TITLE
Set sensible permissions on generated configs

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/hades#69]
Currently, all the files generated with `hades-generate-config.py` are created in python by just using `open()` leaving them with the default mode `-rw-r--r--`, which makes them world-readable. This is not desirable for files containing secrets, such as `auth_vrrp/keepalived.conf`, wich contains the VRRP-Password.

I propose to add a `mode` argument to `hades-generate-config.py` and to change invocations in the systemd unit files by adding  `--mode=600`.

Example ([hades-auth-vrrp.service](https://github.com/agdsn/hades/blob/master/conf/hades-auth-vrrp.service.in)): 

change
```systemd
ExecStartPre=@bindir@/hades-generate-config auth-keepalived.conf.j2 @pkgrunstatedir@/auth-vrrp/keepalived.conf
```
to
```systemd
ExecStartPre=@bindir@/hades-generate-config --mode=600 auth-keepalived.conf.j2 @pkgrunstatedir@/auth-vrrp/keepalived.conf
```

**Comment by sebschrader** [comment]
Good idea.

**Comment by lukasjuhrich** [comment]
@sebschrader where has this been fixed?

**Comment by sebschrader** [comment]
On February 5, 2018 1:32:22 PM UTC, Lukas Juhrich <notifications@github.com> wrote:
>@sebschrader where has this been fixed?

It's been implemented in 2d7c459, but apparently I forgot to mention the issue in the message.
--
Viele Grüße,
Sebastian Schrader

Sent from mobile. Please excuse my brevity.

**Comment by sebschrader** [comment]
It's been implemented in 2d7c459, but apparently I forgot to mention the issue in the message.

**Comment by sebschrader** [comment]
Home directories under `/var/lib/hades` and the config directory `/etc/hades` is still world-readable.

**Comment by sebschrader** [comment]
This has been addressed.
