### ISSUE TITLE
Add posibility to whitelist/integrate web services into the captive portal

### ISSUE THREAD

**Issue by sebschrader** [agdsn/hades#8]
Right now the captive portal is simply displaying the error message and that's it.

We should allow our users to help themselves, if they can, through the self-service web-services, we provide, such as [SIPA](https://github.com/agdsn/sipa).

This could be done by integrating the web services into the captive-portal under specific endpoints through e.g. reverse-proxying or the capability to whitelist certain hosts/domains. We probably need both.

**Comment by fgrsnau** [comment]
Will be tackled by PR #20.

**Comment by sebschrader** [comment]
Closed by #20
